site_name: DETA Manual
repo_name: 'detahq/docs'
repo_url: 'https://github.com/detahq/docs'
theme: 
  name: material
  palette:
    primary: 'grey'
    accent: 'pink'
  font:
    text: Avenir
    code: Fira
  logo: '/images/logo.svg'
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.tilde
extra:
  social:
    - type: 'home'
      link: 'https://web.deta.sh'
extra_css:
  - css/extra.css
nav:
  - Getting Started: index.md
  - Concepts: concepts.md
  - Teletype Commands: teletype.md
  - The DETA Library & Resources: DETA_lib.md
  - Installing Packages: packages.md
  - Example Apps: examples.md
