site_name: DETA Manual
repo_name: 'deta/manual'
repo_url: 'https://github.com/deta/manual'
theme: 
  name: material
  palette:
    primary: 'grey'
    accent: 'pink'
  font:
    text: Questrial
    code: Fira Mono
  logo: '/images/logo.svg'
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - codehilite
  - pymdownx.inlinehilite

extra:
  social:
    - type: 'home'
      link: 'https://web.deta.sh'
extra_css:
  - css/extra.css
nav:
  - Getting Started: index.md
  - Using your programs: 
    - Teletype (CLI): use/run.md
    - Schedule (cron): use/cron.md
    - HTTP / Webhook: use/http.md

  - Python docs:
    - Run (Teletype): python/lib/run.md
    - HTTP: python/lib/http.md
    - Cron: python/lib/cron.md
    - Responses: python/lib/responses.md
    - Web Frameworks: python/frameworks.md
    - Packages (PIP): python/packages.md
    - Resources:
      - Database: python/resources/database.md
      - Cloud Files: python/resources/files.md
      - Email: python/resources/email.md
  - Node.js docs:
    - Run (Teletype): node/lib/run.md
    - HTTP: node/lib/http.md
    - Cron: node/lib/cron.md
    - Web Frameworks: node/frameworks.md
    - Packages (NPM): node/packages.md
    - Resources:
      - Database: node/resources/database.md
      - Cloud Files: node/resources/files.md
      - Email: node/resources/email.md
  - The Runtime: runtime.md
  - User Permissions: permissions.md
  - Authentication: auth.md
  - Debugging: debug.md
  - Teletype Commands (CLI): teletype.md
  - Contact/Feedback: contact.md