site_name: DETA Manual
repo_name: 'deta/manual'
repo_url: 'https://github.com/deta/manual'
theme: 
  name: material
  palette:
    primary: 'grey'
    accent: 'pink'
  font:
    text: Questrial
    code: Fira Mono
  logo: '/images/logo.svg'
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - codehilite

extra:
  social:
    - type: 'home'
      link: 'https://web.deta.sh'
extra_css:
  - css/extra.css
nav:
  - Overview (Video): overview.md
  - Tutorial (Getting Started): tutorial.md
  - Using your programs: using.md
  - DETA SDK (deta.lib):
    - Run (command line): lib/run.md
    - HTTP: lib/http.md
    - Cron: lib/cron.md
    - Invoke (call other programs): lib/invoke.md
    - Responses: lib/responses.md
  - Resources:
    - Database: resources/database.md
    - Cloud Files: resources/files.md
    - Email: resources/email.md
    - The Runtime: resources/runtime.md
  - Sharing Programs (Video): sharing.md
  - Debugging (Video): debug.md
  - Installing Packages: packages.md
  - Teletype Commands (CLI): teletype.md
  - Contact/Feedback: contact.md