site_name: DETA Manual
repo_name: 'deta/docs'
repo_url: 'https://github.com/deta/docs'
theme: 
  name: material
  palette:
    primary: 'grey'
    accent: 'pink'
  font:
    text: Questrial
    code: Fira Mono
  logo: '/images/logo.svg'
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - codehilite

extra:
  social:
    - type: 'home'
      link: 'https://web.deta.sh'
extra_css:
  - css/extra.css
nav:
  - Tutorial: tutorial.md
  - Overview (Video): overview.md
  - Resources:
    - Database: database.md
    - Cloud Files: files.md
    - Email: email.md
    - The Runtime: runtime.md
  - Triggers: triggers.md
  - DETA SDK (deta.lib):
    - Run (command line): run.md
    - HTTP: http.md
    - Cron: cron.md
    - Invoke (call other programs): invoke.md
    - Responses: responses.md
  - Sharing Programs (Video): sharing.md
  - Debugging (Video): debug.md
  - Installing Packages: packages.md
  - Teletype Commands (CLI): teletype.md